services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: suplr-backend:latest
    container_name: suplr-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    network_mode: host
