services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suplr-backend
    network_mode: host
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties:ro
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/app/config/
    restart: unless-stopped
